version: '3'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=elastic_cluster1
      - discovery.zen.ping.unicast.hosts=es2,es3
      - bootstrap.memory_lock=false
      - path.repo=/tmp/backup
        #- "ES_JAVA_OPTS=-Xms512m -Xms512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - /tmp/data1:/usr/share/elasticsearch/data
      - /tmp/backup:/tmp/backup  
    ports:
      - 9200:9200
    networks:
      - elastic
            
  e2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es2
    environment:
      - node.name=es2
      - cluster.name=elastic_cluster1
      - discovery.zen.ping.unicast.hosts=es1,es3
      - bootstrap.memory_lock=false
      - path.repo=/tmp/backup      
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - /tmp/data2:/usr/share/elasticsearch/data
      - /tmp/backup:/tmp/backup  
    networks:
      - elastic
   
  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es3
    environment:
      - node.name=es3
      - cluster.name=elastic_cluster1
      - discovery.zen.ping.unicast.hosts=es1,es2
      - bootstrap.memory_lock=false
      - path.repo=/tmp/backup
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - /tmp/data3:/usr/share/elasticsearch/data
      - /tmp/backup:/tmp/backup  
    networks:
      - elastic

  cerebro1:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    networks:
      - elastic     

networks:
  elastic:
    driver: bridge
